# -*- coding: utf-8 -*-
"""Project 1 Cassandra Goto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16YtHrIRh-i8NMBMzKi1mlGybFQNUBsvs
"""

from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Set the working directory to your Project_1 folder
os.chdir('/content/drive/MyDrive/Decode_Labs/Project_1 ')

# Verify the file exists
print("Current Directory:", os.getcwd())
print("Files in this folder:", os.listdir())

import pandas as pd
import numpy as np
from datetime import datetime

# Load the dataset
df = pd.read_excel('Dataset for Data Analytics.xlsx')

# Initialize a list to track all changes for the change log
change_log = []

# 1. REMOVE DUPLICATES
initial_rows = len(df)
df = df.drop_duplicates(subset=['OrderID'], keep='first')
final_rows = len(df)
duplicates_removed = initial_rows - final_rows
change_log.append({
    'Change_ID': 'CR001',
    'Description': f'Removed duplicate OrderID records',
    'Impact': f'Removed {duplicates_removed} duplicate row(s). Preserved {final_rows} unique records.',
    'Status': 'Resolved'
})

# 2. HANDLE MISSING VALUES
# Count blanks in CouponCode before filling
blank_coupons_before = df['CouponCode'].isna().sum()
df['CouponCode'] = df['CouponCode'].fillna('No Code')
change_log.append({
    'Change_ID': 'CR002',
    'Description': 'Filled missing CouponCode values',
    'Impact': f'Updated {blank_coupons_before} rows from blank to "No Code".',
    'Status': 'Resolved'
})

# Check for any other missing values in critical columns
missing_checks = df[['OrderID', 'CustomerID', 'Product']].isna().sum()
if missing_checks.sum() == 0:
    change_log.append({
        'Change_ID': 'CR003',
        'Description': 'Verified no missing values in critical columns (OrderID, CustomerID, Product)',
        'Impact': 'Confirmed 0 missing values in primary key columns.',
        'Status': 'Resolved'
    })

# 3. CORRECT DATE FORMATS (ISO 8601 YYYY-MM-DD)
df['Date'] = pd.to_datetime(df['Date']).dt.date
change_log.append({
    'Change_ID': 'CR004',
    'Description': 'Standardized Date column to ISO 8601 format (YYYY-MM-DD)',
    'Impact': f'Removed timestamps from {len(df)} rows. All dates now in YYYY-MM-DD format.',
    'Status': 'Resolved'
})

# 4. CORRECT TEXT FORMATS (Proper Case & Trim Whitespace)
text_columns = ['Product', 'PaymentMethod', 'OrderStatus', 'ReferralSource', 'ShippingAddress', 'CustomerID']

for col in text_columns:
    df[col] = df[col].astype(str).str.strip().str.title()

change_log.append({
    'Change_ID': 'CR005',
    'Description': 'Applied Proper Case and trimmed whitespace to all text columns',
    'Impact': f'Standardized casing and spacing for {len(text_columns)} columns across {len(df)} rows.',
    'Status': 'Resolved'
})

# 5. STANDARDIZE PAYMENT METHODS
# Count changes before replacement
online_count_before = (df['PaymentMethod'] == 'Online').sum()
df['PaymentMethod'] = df['PaymentMethod'].replace('Online', 'Online Card')
change_log.append({
    'Change_ID': 'CR006',
    'Description': "Standardized PaymentMethod: Changed 'Online' to 'Online Card'",
    'Impact': f'Updated {online_count_before} rows for consistency with other payment methods.',
    'Status': 'Resolved'
})

# 6. CORRECT NUMERIC PRECISION (Round to 2 decimals)
numeric_cols = ['UnitPrice', 'TotalPrice', 'Quantity']
for col in numeric_cols:
    df[col] = df[col].round(2)

change_log.append({
    'Change_ID': 'CR007',
    'Description': 'Rounded numeric columns to 2 decimal places',
    'Impact': f'Fixed floating-point precision for {len(numeric_cols)} columns: {", ".join(numeric_cols)}.',
    'Status': 'Resolved'
})

# 7. FINAL VERIFICATION (Zero Error Rate on Critical Columns)
duplicate_check = df['OrderID'].duplicated().sum()
date_format_check = df['Date'].apply(lambda x: type(x) == datetime.date).all()

verification_notes = []
if duplicate_check == 0:
    verification_notes.append('Zero duplicate OrderIDs confirmed.')
else:
    verification_notes.append(f'WARNING: {duplicate_check} duplicate OrderIDs found.')

if date_format_check:
    verification_notes.append('All dates are in proper date format.')
else:
    verification_notes.append('WARNING: Some dates may not be properly formatted.')

change_log.append({
    'Change_ID': 'CR008',
    'Description': 'Final verification of data integrity',
    'Impact': f'Duplicate OrderIDs: {duplicate_check}. Date format check: {"Passed" if date_format_check else "Failed"}.',
    'Status': 'Resolved'
})

# 8. GENERATE CHANGE LOG DATAFRAME
change_log_df = pd.DataFrame(change_log)

# 9. SAVE CLEANED DATASET AND CHANGE LOG
# Save the cleaned dataset
df.to_excel('Project1_Data_Cleaned.xlsx', index=False)

# Save the change log as a separate Excel sheet in the same file
with pd.ExcelWriter('Project1_Data_Cleaned.xlsx', engine='openpyxl', mode='a') as writer:
    change_log_df.to_excel(writer, sheet_name='Change_Log', index=False)

# Also save a standalone CSV for easy viewing
df.to_csv('Project1_Data_Cleaned.csv', index=False)

# 10. PRINT SUMMARY REPORT
print("=" * 60)
print("PROJECT 1: DATA CLEANING COMPLETE")
print("=" * 60)
print(f"\nOriginal Dataset:")
print(f"  - Total Rows: {initial_rows}")
print(f"  - Total Columns: {len(df.columns)}")
print(f"\nCleaned Dataset Saved To:")
print(f"  - /content/drive/My Drive/Decode_Labs/Project_1/Project1_Data_Cleaned.xlsx")
print(f"  - /content/drive/My Drive/Decode_Labs/Project_1/Project1_Data_Cleaned.csv")
print(f"\nChange Log Generated:")
print(f"  - {len(change_log_df)} changes documented and saved in the 'Change_Log' sheet.")
print(f"\nFinal Verification:")
for note in verification_notes:
    print(f"  - {note}")
print("\n" + "=" * 60)
print("Cleaned files in Google Drive folder.")
print("=" * 60)